1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [5]:
import numpy as np

def test_none_zero(arr):
    return np.all(arr != 0)
arr = np.array([1, 2, 3, 4, 5])
print(test_none_zero(arr))
arr = np.array([0, 2, 3, 4, 5])
print(test_none_zero(arr))

True
False


2. Write a NumPy program to test whether any of the elements of a given array is non-zero

In [6]:
import numpy as np

def test_any_non_zero(arr):
    return np.any(arr != 0)

arr = np.array([0, 0, 0, 0, 0])
print(test_any_non_zero(arr))

arr = np.array([1, 0, 3, 0, 5])
print(test_any_non_zero(arr))

False
True


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given

In [7]:
import numpy as np

def element_wise_equal(arr1, arr2, tol=0):
    if tol == 0:
        return arr1 == arr2
    else:
        return np.abs(arr1 - arr2) <= tol

arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([1.0, 2.0, 3.0, 4.1])

print(element_wise_equal(arr1, arr2))

print(element_wise_equal(arr1, arr2, tol=0.1))

[ True  True  True False]
[ True  True  True  True]


4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [8]:
import numpy as np

def create_array():
    arr = np.zeros(10, dtype=int)
    arr[:10] = 0
    arr[10:20] = 1
    arr[20:] = 5
    return arr

print(create_array())

[0 0 0 0 0 0 0 0 0 0]


5. Write a NumPy program to create an array of the integers from 30 to70.


In [9]:
import numpy as np

def create_array():
    return np.arange(30, 71)
print(create_array())

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


6. Write a NumPy program to create a 3x3 identity matrix

In [10]:
import numpy as np

def create_identity_matrix():
    return np.eye(3)
print(create_identity_matrix())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Write a NumPy program to generate a random number between 0 and 1

In [11]:
import numpy as np

def generate_random_number():
    return np.random.rand()
print(generate_random_number())

0.6288655315985369


8. Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution

In [12]:
import numpy as np

def generate_random_numbers():
    return np.random.randn(15)

print(generate_random_numbers())

[ 1.08961168  0.68047061  0.22533847 -0.3306082   0.43003182 -0.18194307
  1.45748027  0.17433456  1.40159973 -1.37037203 -0.41449517 -1.13714398
  0.26254308 -1.31285545 -0.09711416]


9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last

In [13]:
import numpy as np

def create_vector():
    vec = np.arange(15, 56)
    print(vec[1:-1])

create_vector()

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [14]:
import numpy as np

def create_vector():
    vec = np.zeros(5, dtype=int)
    vec[:] = np.random.randint(0, 11, size=5)
    print(vec)

create_vector()

[9 1 3 3 4]


11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0.


In [15]:
import numpy as np

def create_matrix():
    mat = np.ones((10, 10))
    mat[1:-1, 1:-1] = 0
    print(mat)
create_matrix()

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.


In [16]:
import numpy as np

def create_matrix():
    mat = np.zeros((5, 5))
    np.fill_diagonal(mat, np.arange(1, 6))
    print(mat)

create_matrix()

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.


In [17]:
import numpy as np

def create_matrix():
    mat = np.zeros((4, 4))
    np.fill_diagonal(mat, 0)
    mat[::2, 1::2] = 1
    mat[1::2, ::2] = 1
    print(mat)

create_matrix()

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)
and load it.


In [18]:
import numpy as np

def save_arrays(array1, array2, filename):
    np.savez_compressed(filename, array1=array1, array2=array2)

def load_arrays(filename):
    data = np.load(filename)
    return data['array1'], data['array2']

array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
save_arrays(array1, array2, 'arrays.npz')
loaded_array1, loaded_array2 = load_arrays('arrays.npz')
print(loaded_array1)
print(loaded_array2)

[1 2 3 4]
[5 6 7 8]


15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
Select

In [19]:
import numpy as np

def create_array():
    return np.random.rand(40)
array = create_array()
print(array)

[0.2172398  0.90470952 0.51048283 0.5326507  0.65047275 0.06712021
 0.7562854  0.69998659 0.61227871 0.92436096 0.33484123 0.08881001
 0.4304325  0.68129481 0.79747417 0.84253549 0.52804901 0.18610879
 0.0292261  0.98942761 0.95703389 0.08836225 0.58886933 0.03308832
 0.1206657  0.99461964 0.51521562 0.50607221 0.58689305 0.48006183
 0.91442898 0.25472985 0.06114737 0.62276332 0.96394691 0.53104388
 0.93101937 0.88909622 0.96188372 0.41258659]


16. Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.

In [20]:
import numpy as np

def extract_numbers(array, num):
    return array[array < num], array[array > num]

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
less_than_5, greater_than_5 = extract_numbers(array, 5)
print("Numbers less than 5:", less_than_5)
print("Numbers greater than 5:", greater_than_5)

Numbers less than 5: [1 2 3 4]
Numbers greater than 5: [ 6  7  8  9 10]
